### PR TITLE
Support vendor-prefixes & old syntax

### PR DESCRIPTION
**Pull request by GlenDC**
I quite like the flex layout, and I might use it for my UI of _Trixel_, the editor I'm writing. That is if I find a satisfying solution to also add a system for some more responsive design rules.

Basically I added vendor prefixes and old syntax based on [mastastealth/sass-flex-mixin](https://github.com/mastastealth/sass-flex-mixin). In that repository I also noticed that there i some stuff that they support, that's not being used in this library. Is that on purpose or is there just some stuff that we don't expose yet?

Hopefully this gets it into the main branch relatively soon.

cheers

### CODE REVIEW

**Comment by GlenDC** [comment]
This should also solve issue #4.

**Comment by TheSeamau5** [comment]
Cool! Did you test it on multiple browsers?

**Comment by GlenDC** [comment]
No thanks for reminding me of that. I did just now. The flex-stuff itself seems to be fine, but for some reason the background style of the first examples seems to dissapear from the final css on both firefox and safari. Chrome seems to be fine.

**Comment by GlenDC** [comment]
There seems to be more problems than that. I'll take a look at of it somewhere late tonight, and hopefully I find what's wrong. Sorry for the inconvenience, should have tested better, really. My bad.

**Comment by GlenDC** [comment]
@TheSeamau5, I'm now supporting all the flex styles as properties. And thanks to the Vendor-module dependency it now works nicely on all browsers.

Would love to hear your feedback & input on the current state of the library.
As I have a weird feeling with the higher level functions we provide, but I can't put my finger on it, perhaps you can.

**Comment by TheSeamau5** [comment]
I think the weird feeling you have is that the functions all wrap divs.

So, they're usually:

``` elm
f : Html -> Html
f element = 
   div 
     [ style someCustomWrapperStyles ]
     [ element ]
```

I think that this approach is weird (and I'm totally to blame for this).

What I was thinking is that instead we should move towards producing something like a `Style` type (what you call `StringPairList`)

``` elm
type alias Style = List (String, String)
```

From there we can just produce styles with simple composable functions like

``` elm

setDimensions : Float -> Float -> Style 
setDimensions width height = 
  [ "width" => toString width ++ "px"
  , "height" => toString height ++ "px"
  ]

```

And these styles can just be merged with `++`

So, 

``` elm

myStyle = 
  flexContainer
  ++ centeredChildren
  ++ setDimensions 100 200 
  ++ fontFamily "Helvetica, Arial, sans-serif"
  ++ absolutelyPositioned
```

Then, anyone can make these styles, which we could call "mixins", and mix them from different libraries.

With the current approach by flex-html, doing something like this would mean your creating 5 extra divs, which is totally unnecessary and could possible lead to unintended behavior... cuz CSS...

**Comment by GlenDC** [comment]
I was thinking of making an elm-style module that does stuff like that for
general purposes, so nothing as specialised as flex-html.

So would it be OK for me to remove these high level features from flex-html
and instead keep the focus on the mixins?

Also you seem to describe such a mixing as something that just produces
style input, rather than a functioned meant as piping, as I implemented
them now.

Is that because you prefer it like that, and if so, why?

**Comment by TheSeamau5** [comment]
Yup, it would be OK for you to remove the higher level features and focus on the mixins. I think it would be best if you decide to make elm-style as they would go nicely together.

As for the piping, I don't know, I guess it's a choice and either way seems fine. I think from a usability perspective it makes more sense to not do the piping. Cuz if we do the piping, it may seem like there is no way to just make a style. All you have are functions to transform styles. So, you'd need somewhere to say that one starts from an empty list... which sorta makes very little sense. I guess I'm taking my cues from `Graphics.Collage` which only has functions to produce `Form` instead of functions that take forms and make new ones.

We could then add the function `merge`:

``` elm
merge : List Style -> Style
```

which is just `List.concat`

and this would allow us to integrate mixins as follows

``` elm
myStyles = 
  merge
    [ absolutelyPositioned
    , setDimensions 100 200 
    , verticallyCenteredMixin
    , horizontallyCenteredMixin
    , clearMarginPaddingMixin
    ]

```

I dunno, I guess I just find this more readable. I acknowledge that our opinions may differ on this one, and as I said, either way is fine.

**Comment by GlenDC** [comment]
Cool, I'm happy with the module as it is right now @TheSeamau5.
I'll start writing the _elm-style_ module tomorrow.

If you're happy with the current state of flex-html, you can concider my work done and merge it in the mainline. Otherwise please let me know what's wrong and/or should be changed.

**Comment by TheSeamau5** [comment]
Cool, final nitpick, in order to follow the [API Design Guidelines](http://package.elm-lang.org/help/design-guidelines#module-names-should-not-reappear-in-function-names), it would be cool to remove the word "flex" from the functions except from the ones where it's impossible like "flex"

For example `flexDirection` -> `direction`. According to the guidelines, the rationale here is to avoid having to say `Flex.flexDirection` and just say `Flex.direction`.

If this is too much, I can just merge and then perform the changes myself. It's all the same to me.

And, thanks a lot for your help. If you need any help with elm-style, don't hesitate to ask.

**Comment by GlenDC** [comment]
Nice suggestion @TheSeamau5, that API improvement has happened.
In the meanwhile I also updated the readme file to reflect the new API and updated examples.

And thanks, I'll make sure to mail you with a link to the repository once I'm ready for some advice and/or help :)

**Comment by TheSeamau5** [comment]
Cool. Thanks for everything.

**Comment by vilterp** [comment]
Nice work! This Elm CSS module already exists, not sure if it's what you want:

http://package.elm-lang.org/packages/identicalsnowflake/elm-typed-styles/2.0.0

**Comment by GlenDC** [comment]
Ah yes @vilterp that comes close to what I had in mind. It is however very inactive and incomplete.

**Comment by vilterp** [comment]
Whoops, I meant to link to this one http://package.elm-lang.org/packages/adam-r-kowalski/Elm-Css/1.0.1 which is more active & complete

**Comment by GlenDC** [comment]
yeah I noticed it today, going to try to help him with issus and suggestions.

**Pull request merged**
